# Generated by Django 3.1 on 2020-08-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackproduct_app', '0002_auto_20200824_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.OneToOneField(default='AnonymousUser', on_delete=django.db.models.deletion.CASCADE, to='blackproduct_app.bpruser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(max_length=1001, upload_to='media'),
        ),
    ]
