# Generated by Django 3.1.1 on 2020-09-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackproduct_app', '0004_auto_20200913_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpruser',
            name='saved_businesses',
            field=models.ManyToManyField(related_name='_bpruser_saved_businesses_+', to='blackproduct_app.Business'),
        ),
        migrations.AddField(
            model_name='bpruser',
            name='saved_products',
            field=models.ManyToManyField(related_name='favorites', to='blackproduct_app.Product'),
        ),
    ]
