# Generated by Django 3.1.1 on 2020-09-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackproduct_app', '0005_auto_20200913_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_choice',
            field=models.CharField(choices=[('HCSC', 'Hair Care/Skincare'), ('HHS', 'Household Staples'), ('F&D', 'Food & Drink')], default='HCSC', max_length=4),
        ),
    ]
