# Generated by Django 3.1.1 on 2020-09-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackproduct_app', '0006_product_product_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_or_dislike',
        ),
    ]
