# Generated by Django 3.1.1 on 2020-09-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackproduct_app', '0007_remove_product_like_or_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpruser',
            name='is_review_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bpruser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
